GET http://localhost:8080/produto
Accept: application/json

###
POST http://localhost:8080/produto
Content-Type: application/json

{
  "name": "Product Number 0",
  "image": "//imagens.pontofrio.com.br/Control/ArquivoExibir.aspx?IdArquivo=6670538",
  "oldPrice": 363,
  "price": 332,
  "description": "Product long description number 0 just to make more than one like of text."

}

###
